#!/bin/sh
#
### BEGIN INIT INFO
# Provides: fractal-explorer
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

case "$1" in
  start)
        . /etc/profile
        fractal-explorer
  ;;

  stop)
        pid=`/bin/pidof $1`
        [ "$pid" != "" ] && kill $pid
  ;;

  restart)
	$0 stop
        sleep 1
        $0 start
  ;;

  *)
        echo "usage: $0 { start | stop | restart }"
  ;;
esac

exit 0
