#!/bin/sh
### BEGIN INIT INFO
# Provides:       fractal-explorer
# Required-Start: $local_fs $remote_fs
# Required-Stop:  $local_fs $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
### END INIT INFO

cmd="/usr/bin/fractal-explorer"

case "$1" in
  start)
    if [ -z "$(/bin/pidof $cmd)" ]; then
      . /etc/profile

      for _ in $(seq 10); do
        if [ -e /dev/input/js0 ]; then
          break
        fi
        sleep 1
      done

      $cmd &
    fi
    ;;

  stop)
    pid="$(/bin/pidof $cmd)"
    if [ -n "$pid" ]; then
      kill "$pid"
    fi
    ;;

  restart)
    $0 stop
    sleep 1
    $0 start
    ;;

  *)
    echo "usage: $0 { start | stop | restart }"
    ;;
esac

exit 0
